services:
  db:
    image: postgres
    platform: linux/amd64
    container_name: split-backend-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USERNAME -d $$POSTGRES_DB" ]
      interval: 5s
  ktor:
    build: .
    platform: linux/amd64
    container_name: split-backend-ktor
    ports:
      - "8080:8080"
    env_file:
      - postgres.env
    depends_on:
      - db

volumes:
  pg-volume: {}